### ISSUE TITLE
python setup.py start之后没有抓取数据

### ISSUE THREAD

**Issue by Chen-DaYi** [shancang/spider#1]
你好，我运行python setup.py start之后：Spider Started .... PID 66867，但是没有爬取数据，用python setup.py status查看状态发现程序很快就结束。请问还需要其他操作不？
另外是否需要自己准备pid文件，我没有这个文件/tmp/spider/spider.pid。
log里打：

> 2016-10-09 17:44:04,191  daemonize.py  [line:242] WARNING  Starting daemon.
> 2016-10-09 17:44:04,191  spider.py  [line:203] INFO  start spider.....
> 2016-10-09 17:44:16,391  daemonize.py  [line:70] WARNING  Stopping daemon.

是不是需要在setup.py文件中加入生成和写入pid的语句？

**Comment by shancang** [comment]
请参考此博客
http://sandy521.blog.51cto.com/5728588/1812623

不需要自己准备pid ，只需在config.py里面配置相应的pid 文件即可

**Comment by ghost** [comment]
我也遇到了同样的问题，没有找到/tmp/spider/spider.pid这个文件。没有pid文件，在config.py中如何指定pid文件位置呢？

**Comment by shancang** [comment]
现在这个项目已经不适用了，官方数据结构有变化，目前没时间维护谢谢！
