### ISSUE TITLE
解析汽车配置时会出错

### ISSUE THREAD

**Issue by chenguowei** [shancang/spider#3]
使用models = v[u"车型名称"]，会出现KeyError错误，要使用models = v.get(u"车型名称")才不会错误
在插入数据库的时候，由于某些字段没有进行相应的处理，某些字段包含‘’单引号，会导致插入失败

**Comment by shancang** [comment]
感谢，这个v.get(u"车型名称","")这种确实合适！因为当初做的一个练手项目，一直没有更新，很多地方很low 请谅解！

2017-04-25 

chenshancang 



发件人：chen <notifications@github.com>
发送时间：2017-04-24 19:54
主题：[shancang/spider] 解析汽车配置时会出错 (#3)
收件人："shancang/spider"<spider@noreply.github.com>
抄送："Subscribed"<subscribed@noreply.github.com>

使用models = v[u"车型名称"]，会出现KeyError错误，要使用models = v.get(u"车型名称")才不会错误
在插入数据库的时候，由于某些字段没有进行相应的处理，某些字段包含‘’单引号，会导致插入失败
